name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Deploy to server
        run: |
          ssh usuario@IP_SERVIDOR "
          cd /var/www/html/tu-app &&
          git pull origin main &&
          composer install --no-dev --optimize-autoloader &&
          systemctl restart apache2
          "
